### ISSUE TITLE
Unable to Login

### ISSUE THREAD

**Issue by Nitesh-18** [ducheharsh/medium-project#1]
![Screenshot 2024-08-15 171216](https://github.com/user-attachments/assets/db498c29-f1e5-4250-a04e-05645dd0da28)

**Comment by ducheharsh** [comment]
Due to inactivity cloudflare worker must be stopped, I'll spin up the worker soon

**Comment by ducheharsh** [comment]
It must be up now, Thanks for informing 💡

**Comment by Nitesh-18** [comment]
Yep it does work !
